server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1904a?characterEncoding=UTF-8&serverTimezone = GMT
    username: root
    password: amdin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # \u91CD\u8981\u914D\u7F6E
  type-aliases-package: com.fh.vue.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  # \u6253\u5370sql
